eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
  instance:
    preferIpAddress: false
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}