server:
  port: 8082
spring:
  application:
    name: movie-info-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
api:
  key: 8dfe5fc4bf3a1e6cc067d05bbabdb04d